# Generated by Django 5.2.17 on 2026-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
