# Generated by Django 5.2.17 on 2026-09-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roommessage_is_deleted_roommessage_is_edited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
