# Generated by Django 5.2.5 on 2025-09-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='two_fator_code',
            new_name='two_factor_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='two_fator_code_created_at',
            new_name='two_factor_code_created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='two_fator_enabled',
            new_name='two_factor_enabled',
        ),
    ]
